### ISSUE TITLE
Expose TS types from the lib?

### ISSUE THREAD

**Issue by estorski** [boschni/server-mockr#2]
Hey Niek,

Currently if I try to auto-import `HeadersValue` type for example, it gets resolved by VSCode like this:
```
import { HeadersValue } from 'server-mockr/dist/mock-server/Values';
```

Do you think it's a bad idea to expose them directly from `server-mockr`?

**Comment by boschni** [comment]
Hi! Yes these could definitely be useful for consumers. I have exposed the types in version `1.1.0`.
